// Code generated by go-swagger; DO NOT EDIT.

package query

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"

	"github.com/go-openapi/swag"
)

// GetQueryLanguageStatusURL generates an URL for the get query language status operation
type GetQueryLanguageStatusURL struct {
	Language string
	Status   string

	Languages []string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetQueryLanguageStatusURL) WithBasePath(bp string) *GetQueryLanguageStatusURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetQueryLanguageStatusURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *GetQueryLanguageStatusURL) Build() (*url.URL, error) {
	var result url.URL

	var _path = "/query/{language}/{status}"

	language := o.Language
	if language != "" {
		_path = strings.Replace(_path, "{language}", language, -1)
	} else {
		return nil, errors.New("Language is required on GetQueryLanguageStatusURL")
	}

	status := o.Status
	if status != "" {
		_path = strings.Replace(_path, "{status}", status, -1)
	} else {
		return nil, errors.New("Status is required on GetQueryLanguageStatusURL")
	}

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/v1"
	}
	result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var languagesIR []string
	for _, languagesI := range o.Languages {
		languagesIS := languagesI
		if languagesIS != "" {
			languagesIR = append(languagesIR, languagesIS)
		}
	}

	languages := swag.JoinByFormat(languagesIR, "multi")

	for _, qsv := range languages {
		qs.Add("languages", qsv)
	}

	result.RawQuery = qs.Encode()

	return &result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *GetQueryLanguageStatusURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *GetQueryLanguageStatusURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *GetQueryLanguageStatusURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on GetQueryLanguageStatusURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on GetQueryLanguageStatusURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *GetQueryLanguageStatusURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
