// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi i18n Api

    Schemes:
      http
    Host: 127.0.0.1:7082
    BasePath: /v1
    Version: 1.0.0

    Consumes:
    - application/json
    - multipart/form-data

    Produces:
    - application/json

swagger:meta
*/
package restapi
