// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "i18n Api",
    "version": "1.0.0"
  },
  "host": "127.0.0.1:8080",
  "basePath": "/v1",
  "paths": {
    "/key": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Operation"
        ],
        "summary": "更新获保存新的LanguageKey",
        "operationId": "SaveOrUpdateKey",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Fail",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    },
    "/query/{language}/{status}": {
      "get": {
        "produces": [
          "application/json",
          "text/plain"
        ],
        "tags": [
          "Query"
        ],
        "summary": "下载语言列表",
        "parameters": [
          {
            "type": "string",
            "description": "all(全部)",
            "name": "language",
            "in": "path",
            "required": true
          },
          {
            "enum": [
              "all",
              "unset",
              "settled"
            ],
            "type": "string",
            "name": "status",
            "in": "path",
            "required": true
          },
          {
            "type": "array",
            "items": {
              "type": "string"
            },
            "collectionFormat": "multi",
            "name": "languages",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/LanguageAPIModel"
              }
            }
          },
          "400": {
            "description": "Fail",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    },
    "/upload": {
      "put": {
        "consumes": [
          "multipart/form-data"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Operation"
        ],
        "summary": "上传翻译项",
        "operationId": "Upload",
        "parameters": [
          {
            "type": "file",
            "name": "file",
            "in": "formData"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Fail",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "LanguageAPIModel": {
      "type": "object",
      "properties": {
        "default": {
          "type": "string"
        },
        "items": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "location": {
                "type": "string"
              },
              "text": {
                "type": "string"
              }
            }
          }
        },
        "key": {
          "type": "string"
        }
      }
    }
  },
  "tags": [
    {
      "name": "Operation"
    },
    {
      "name": "Query"
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "i18n Api",
    "version": "1.0.0"
  },
  "host": "127.0.0.1:8080",
  "basePath": "/v1",
  "paths": {
    "/key": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Operation"
        ],
        "summary": "更新获保存新的LanguageKey",
        "operationId": "SaveOrUpdateKey",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Fail",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    },
    "/query/{language}/{status}": {
      "get": {
        "produces": [
          "application/json",
          "text/plain"
        ],
        "tags": [
          "Query"
        ],
        "summary": "下载语言列表",
        "parameters": [
          {
            "type": "string",
            "description": "all(全部)",
            "name": "language",
            "in": "path",
            "required": true
          },
          {
            "enum": [
              "all",
              "unset",
              "settled"
            ],
            "type": "string",
            "name": "status",
            "in": "path",
            "required": true
          },
          {
            "type": "array",
            "items": {
              "type": "string"
            },
            "collectionFormat": "multi",
            "name": "languages",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/LanguageAPIModel"
              }
            }
          },
          "400": {
            "description": "Fail",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    },
    "/upload": {
      "put": {
        "consumes": [
          "multipart/form-data"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Operation"
        ],
        "summary": "上传翻译项",
        "operationId": "Upload",
        "parameters": [
          {
            "type": "file",
            "name": "file",
            "in": "formData"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Fail",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "LanguageAPIModel": {
      "type": "object",
      "properties": {
        "default": {
          "type": "string"
        },
        "items": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "location": {
                "type": "string"
              },
              "text": {
                "type": "string"
              }
            }
          }
        },
        "key": {
          "type": "string"
        }
      }
    }
  },
  "tags": [
    {
      "name": "Operation"
    },
    {
      "name": "Query"
    }
  ]
}`))
}
