// Code generated by go-swagger; DO NOT EDIT.

package operation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// SaveOrUpdateKeyHandlerFunc turns a function with the right signature into a save or update key handler
type SaveOrUpdateKeyHandlerFunc func(SaveOrUpdateKeyParams) middleware.Responder

// Handle executing the request and returning a response
func (fn SaveOrUpdateKeyHandlerFunc) Handle(params SaveOrUpdateKeyParams) middleware.Responder {
	return fn(params)
}

// SaveOrUpdateKeyHandler interface for that can handle valid save or update key params
type SaveOrUpdateKeyHandler interface {
	Handle(SaveOrUpdateKeyParams) middleware.Responder
}

// NewSaveOrUpdateKey creates a new http.Handler for the save or update key operation
func NewSaveOrUpdateKey(ctx *middleware.Context, handler SaveOrUpdateKeyHandler) *SaveOrUpdateKey {
	return &SaveOrUpdateKey{Context: ctx, Handler: handler}
}

/*SaveOrUpdateKey swagger:route POST /key Operation saveOrUpdateKey

更新获保存新的LanguageKey

*/
type SaveOrUpdateKey struct {
	Context *middleware.Context
	Handler SaveOrUpdateKeyHandler
}

func (o *SaveOrUpdateKey) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewSaveOrUpdateKeyParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
