// Code generated by go-swagger; DO NOT EDIT.

package operation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
)

// NewSaveOrUpdateKeyParams creates a new SaveOrUpdateKeyParams object
// no default values defined in spec.
func NewSaveOrUpdateKeyParams() SaveOrUpdateKeyParams {

	return SaveOrUpdateKeyParams{}
}

// SaveOrUpdateKeyParams contains all the bound params for the save or update key operation
// typically these are obtained from a http.Request
//
// swagger:parameters SaveOrUpdateKey
type SaveOrUpdateKeyParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  In: body
	*/
	Body []string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewSaveOrUpdateKeyParams() beforehand.
func (o *SaveOrUpdateKeyParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body []string
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("body", "body", "", err))
		} else {
			// no validation required on inline body
			o.Body = body
		}
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
