// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// LanguageAPIModel language API model
// swagger:model LanguageAPIModel
type LanguageAPIModel struct {

	// default
	Default string `json:"default,omitempty"`

	// items
	Items []*LanguageAPIModelItemsItems0 `json:"items"`

	// key
	Key string `json:"key,omitempty"`
}

// Validate validates this language API model
func (m *LanguageAPIModel) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateItems(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *LanguageAPIModel) validateItems(formats strfmt.Registry) error {

	if swag.IsZero(m.Items) { // not required
		return nil
	}

	for i := 0; i < len(m.Items); i++ {
		if swag.IsZero(m.Items[i]) { // not required
			continue
		}

		if m.Items[i] != nil {
			if err := m.Items[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("items" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *LanguageAPIModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LanguageAPIModel) UnmarshalBinary(b []byte) error {
	var res LanguageAPIModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// LanguageAPIModelItemsItems0 language API model items items0
// swagger:model LanguageAPIModelItemsItems0
type LanguageAPIModelItemsItems0 struct {

	// location
	Location string `json:"location,omitempty"`

	// text
	Text string `json:"text,omitempty"`
}

// Validate validates this language API model items items0
func (m *LanguageAPIModelItemsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LanguageAPIModelItemsItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LanguageAPIModelItemsItems0) UnmarshalBinary(b []byte) error {
	var res LanguageAPIModelItemsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
